name: Generate website

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/build-setup/**/*'
      - '.github/workflows/generate-website.yml'
      - '.nvmrc'
      - 'packages/core/**/*'
      - 'packages/website/**/*'
      - '!packages/website/README.md'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
  # Allows you to deploy manually to GH Pages from the Actions tab (only if run from the main branch)
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/build-setup/**/*'
      - '.github/workflows/generate-website.yml'
      - '.nvmrc'
      - 'packages/core/**/*'
      - 'packages/website/**/*'
      - '!packages/website/README.md'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'


# Allow one concurrent deployment
# Use a dynamic name to run the workflow in parallel for the build part (in particular in PRs)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Build @maxgraph/core API docs
        run: npm run docs:api -w packages/core
      - name: Build Storybook demo
        run: npm run build -w packages/core -w packages/html
      - name: Copy generated resources to the website
        run: npm run extra:copy-gen-resources -w packages/website
      - name: Build website
        run: npm run build -w packages/website
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/website/build/

  deploy:
    needs: build
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
